Repository YacGroup/yacguide, pull requests merged in 2022-02, with the labels that each got.

#312 Added start-up activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt
  app/src/main/res/drawable/ic_start.xml
  app/src/main/res/layout/activity_launch.xml
Labels: feature

#311 Migrated region list to recycler view
  app/src/main/java/com/yacgroup/yacguide/CountryActivity.kt
  app/src/main/java/com/yacgroup/yacguide/RegionActivity.kt
  app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
  app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
  app/src/main/java/com/yacgroup/yacguide/database/Region.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/RegionViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/network/RegionParser.kt
  app/src/main/res/layout/activity_region_manager.xml
  app/src/main/res/layout/activity_table.xml
Labels: feature

#315 Migrated sector list to recycler view
  app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
  app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
  app/src/main/java/com/yacgroup/yacguide/database/Sector.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/RegionViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/SectorViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt
  app/src/main/res/layout/activity_sector.xml
Labels: feature

#316 Migrated rock list to recycler view
  app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
  app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
  app/src/main/java/com/yacgroup/yacguide/database/Rock.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/RockViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt
  app/src/main/java/com/yacgroup/yacguide/utils/AscendStyle.kt
  app/src/main/res/layout/activity_rock.xml
Labels: feature

#319 Added rock relevance filter
  app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
  app/src/main/java/com/yacgroup/yacguide/TableActivity.kt
  app/src/main/java/com/yacgroup/yacguide/activity_properties/RockSearchable.kt
  app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
  app/src/main/java/com/yacgroup/yacguide/database/RockDao.kt
  app/src/main/java/com/yacgroup/yacguide/database/SqlMacros.kt
  app/src/main/java/com/yacgroup/yacguide/database/comment/RockComment.kt
  app/src/main/java/com/yacgroup/yacguide/utils/IntentConstants.kt
  app/src/main/res/layout/search_dialog.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#321 Possibility to set default region
  app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt
  app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
  app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
  app/src/main/java/com/yacgroup/yacguide/utils/SearchBarHandler.kt
  app/src/main/res/values/setup.xml
  app/src/main/res/values/strings.xml
Labels: feature

#323 Enabled global route search
  app/src/main/java/com/yacgroup/yacguide/CountryActivity.kt
  app/src/main/java/com/yacgroup/yacguide/RegionActivity.kt
  app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
  app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
  app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
  app/src/main/java/com/yacgroup/yacguide/activity_properties/RockSearchable.kt
  app/src/main/java/com/yacgroup/yacguide/activity_properties/RouteSearchable.kt
  app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
  app/src/main/java/com/yacgroup/yacguide/database/RouteDao.kt
  app/src/main/res/layout/rock_search_dialog.xml
  app/src/main/res/layout/route_search_dialog.xml
  app/src/main/res/menu/options_menu.xml
Labels: feature

#318 Added unit tests for country dao
  app/build.gradle
  app/src/androidTest/java/com/yacgroup/yacguide/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/yacgroup/yacguide/TestUtils.kt
  app/src/androidTest/java/com/yacgroup/yacguide/database/Common.kt
  app/src/androidTest/java/com/yacgroup/yacguide/database/CountryDaoTests.kt
  app/src/main/java/com/yacgroup/yacguide/database/CountryDao.kt
  app/src/main/java/com/yacgroup/yacguide/database/RegionDao.kt
  app/src/main/java/com/yacgroup/yacguide/database/SqlMacros.kt
  app/src/test/java/com/yacgroup/yacguide/ExampleUnitTest.kt
  build.gradle
Labels: KTLO

#324 Drop support for API version <26
  app/build.gradle
Labels: feature

#326 Add quality filter for routes
  app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
  app/src/main/java/com/yacgroup/yacguide/activity_properties/RockSearchable.kt
  app/src/main/java/com/yacgroup/yacguide/activity_properties/RouteSearchable.kt
  app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
  app/src/main/java/com/yacgroup/yacguide/database/RouteDao.kt
  app/src/main/java/com/yacgroup/yacguide/database/SqlMacros.kt
  app/src/main/java/com/yacgroup/yacguide/database/comment/RouteComment.kt
  app/src/main/res/layout/route_search_dialog.xml
  app/src/main/res/values/strings.xml
Labels: feature

#327 Set default name for tourbook export
  app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
  app/src/main/res/values/setup.xml
Labels: feature

#332 Added ripple effect to list view items
  app/src/main/res/layout/list_data_item.xml
Labels: feature

#331 Display ascent list below route description
  app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt
  app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt
  app/src/main/java/com/yacgroup/yacguide/TourbookAscendActivity.kt
  app/src/main/java/com/yacgroup/yacguide/database/Ascend.kt
  app/src/main/java/com/yacgroup/yacguide/database/tourbook/TourbookExporter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/AscentViewAdapter.kt
  app/src/main/res/layout/activity_description.xml
  app/src/main/res/layout/activity_tourbook.xml
  app/src/main/res/layout/activity_tourbook_ascend.xml
  app/src/main/res/layout/ascendbar_description.xml
  app/src/main/res/layout/button_download.xml
  app/src/main/res/layout/choose_tourbook.xml
  app/src/main/res/layout/nav_tourbook.xml
  app/src/main/res/layout/route_description.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#329 Refactored search dialog filter spinners
  app/src/main/java/com/yacgroup/yacguide/activity_properties/RockSearchable.kt
  app/src/main/java/com/yacgroup/yacguide/activity_properties/RouteSearchable.kt
  app/src/main/java/com/yacgroup/yacguide/database/comment/RockComment.kt
  app/src/main/java/com/yacgroup/yacguide/database/comment/RouteComment.kt
  app/src/main/java/com/yacgroup/yacguide/utils/FilterSpinner.kt
  app/src/main/java/com/yacgroup/yacguide/utils/FilterSpinnerListener.kt
Labels: KTLO

#330 Added region dao unit tests
  app/build.gradle
  app/src/androidTest/java/com/yacgroup/yacguide/database/Common.kt
  app/src/androidTest/java/com/yacgroup/yacguide/database/RegionDaoTests.kt
  app/src/main/java/com/yacgroup/yacguide/database/RegionDao.kt
  app/src/main/java/com/yacgroup/yacguide/database/SectorDao.kt
Labels: KTLO

#333 Fix mapping from MIME type to file extension for lower API versions
  app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
  app/src/main/java/com/yacgroup/yacguide/database/tourbook/TourbookExportFormat.kt
Labels: bug
