Repository YacGroup/yacguide, pull requests merged in 2023-02, with the labels that each got.

#397 Encircle launch icon after finishing automatic update
  app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt
  app/src/main/res/drawable/ic_start_done.xml
  app/src/main/res/layout/activity_launch.xml
Labels: feature

#400 Sort downloaded regions to top of list
  app/src/main/java/com/yacgroup/yacguide/RegionActivity.kt
Labels: feature

#398 Fixed incorrect handling with default region id
  app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt
  app/src/main/java/com/yacgroup/yacguide/PreferencesActivity.kt
  app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
  app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
  app/src/main/res/values/setup.xml
Labels: bug

#401 Migrate tourbook to nested recycler view
  app/src/androidTest/java/com/yacgroup/yacguide/database/RegionDaoTests.kt
  app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt
  app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
  app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
  app/src/main/java/com/yacgroup/yacguide/database/RegionDao.kt
  app/src/main/java/com/yacgroup/yacguide/database/SqlMacros.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/AscendDiffCallback.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/AscendViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/SectionViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/SectionViewItem.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/TourbookAscendViewAdapter.kt
  app/src/main/res/layout/list_view_section_content.xml
Labels: KTLO

#402 Make UpdateDialog always-present again
  app/src/main/java/com/yacgroup/yacguide/UpdateHandler.kt
Labels: feature

#405 Added queue for network requests
  app/src/main/java/com/yacgroup/yacguide/UpdateHandler.kt
  app/src/main/java/com/yacgroup/yacguide/network/CountryAndRegionParser.kt
  app/src/main/java/com/yacgroup/yacguide/network/JSONWebParser.kt
  app/src/main/java/com/yacgroup/yacguide/network/NetworkListener.kt
  app/src/main/java/com/yacgroup/yacguide/network/NetworkRequest.kt
  app/src/main/java/com/yacgroup/yacguide/network/NetworkTask.kt
  app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt
Labels: feature

#406 Get rid of database schema export warning
  app/build.gradle
  app/schemas/com.yacgroup.yacguide.database.AppDatabase/1.json
  app/src/main/java/com/yacgroup/yacguide/database/AppDatabase.kt
Labels: KTLO

#407 Unified list adapters to generic list adapter
  app/src/main/java/com/yacgroup/yacguide/CountryActivity.kt
  app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt
  app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
  app/src/main/java/com/yacgroup/yacguide/RegionActivity.kt
  app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
  app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
  app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
  app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
  app/src/main/java/com/yacgroup/yacguide/TableActivity.kt
  app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
  app/src/main/java/com/yacgroup/yacguide/TourbookAscendActivity.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/AscendDiffCallback.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/AscendViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/BaseViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/BaseViewItem.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/CountryViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/ListViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/RegionViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/RockViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/RouteViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/SectionViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/SectorViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/TourbookAscendViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/utils/VisualUtils.kt
  app/src/main/res/layout/list_data_item.xml
Labels: KTLO

#409 Make deprecated package manager API compatible
  app/src/main/java/com/yacgroup/yacguide/extensions/PackageManager.kt
  app/src/main/java/com/yacgroup/yacguide/utils/ActivityUtils.kt
  app/src/main/java/com/yacgroup/yacguide/utils/ContactUtils.kt
Labels: KTLO

#410 Reset lists after parsing in country parser
  app/src/main/java/com/yacgroup/yacguide/network/CountryAndRegionParser.kt
Labels: bug

#408 Use generic list adapter for region manager list
  app/src/main/java/com/yacgroup/yacguide/CountryActivity.kt
  app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
  app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
  app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/BaseViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/BaseViewItem.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/ListViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/SectionViewAdapter.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/SectionViewItem.kt
  app/src/main/java/com/yacgroup/yacguide/list_adapters/SwipeController.kt
  app/src/main/java/com/yacgroup/yacguide/utils/VisualUtils.kt
Labels: KTLO

#412 Update Kotlin, Gradle and library versions
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: KTLO
